<?php

namespace AppBundle\Repository;

/**
 * RemoteSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemoteSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
